services:
  - type: web
    name: dolibarr-middleware
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
