services:
  - type: web
    name: dolibarr-middleware
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - fromGroup: dolibarr-env
      - key: NODE_ENV
        value: production
